const express=require("express")
const app=express()
const urlroute=require("./routes/url.js")
const userroute=require("./routes/user.js")
const staticroute=require("./routes/staticRouter.js")
const cookieParser=require("cookie-parser")
const {connectMongoDB}=require("./connection.js")
const {restrictToLoggedInOnly,checkAuth}=require("./middlewares/auth.js")
const path=require("path")
connectMongoDB("mongodb://127.0.0.1:27017/shortURLs")
app.use(express.json())
app.use(express.urlencoded({extended:false}))
app.use(cookieParser())
app.set("view engine","ejs")
app.set('views',path.resolve("./views"))
app.use("/url",restrictToLoggedInOnly,urlroute)  //this middleware activates whenever the req comes on /url-it ensures that the user is logged-in
app.use("/",checkAuth,staticroute)
app.use("/user",userroute)
app.listen(8888,()=>console.log('Server connected'))
console.log('hey');
